version: '3.11'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh", "-c", "pg_isready" ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
    postgres_data: {}
